/**
 * PDF Generation Engine
 * Uses @react-pdf/renderer to generate compliance documents
 */
import ReactPDF, { Document, Page, Text, View, StyleSheet, Image } from '@react-pdf/renderer';
import type { ReactElement } from 'react';

/**
 * Common styles for all PDF documents
 */
export const commonStyles = StyleSheet.create({
  page: {
    padding: 40,
    fontSize: 10,
    fontFamily: 'Helvetica',
    lineHeight: 1.5,
  },
  header: {
    marginBottom: 20,
    borderBottom: '2 solid #E5E7EB',
    paddingBottom: 15,
  },
  logo: {
    width: 120,
    height: 30,
    marginBottom: 10,
  },
  title: {
    fontSize: 20,
    fontWeight: 'bold',
    marginBottom: 5,
    color: '#111827',
  },
  subtitle: {
    fontSize: 12,
    color: '#6B7280',
    marginBottom: 3,
  },
  section: {
    marginBottom: 15,
  },
  sectionTitle: {
    fontSize: 14,
    fontWeight: 'bold',
    marginBottom: 8,
    color: '#374151',
  },
  text: {
    fontSize: 10,
    color: '#1F2937',
    marginBottom: 5,
  },
  label: {
    fontSize: 9,
    fontWeight: 'bold',
    color: '#6B7280',
    marginBottom: 3,
    textTransform: 'uppercase',
  },
  value: {
    fontSize: 10,
    color: '#111827',
    marginBottom: 8,
  },
  footer: {
    position: 'absolute',
    bottom: 30,
    left: 40,
    right: 40,
    borderTop: '1 solid #E5E7EB',
    paddingTop: 10,
    fontSize: 8,
    color: '#9CA3AF',
  },
  disclaimer: {
    backgroundColor: '#FEF3C7',
    padding: 10,
    marginTop: 15,
    marginBottom: 15,
    borderRadius: 4,
    border: '1 solid #FCD34D',
  },
  disclaimerText: {
    fontSize: 8,
    color: '#92400E',
    lineHeight: 1.4,
  },
  table: {
    marginTop: 10,
    marginBottom: 10,
  },
  tableRow: {
    flexDirection: 'row',
    borderBottom: '1 solid #E5E7EB',
    paddingTop: 8,
    paddingBottom: 8,
  },
  tableHeader: {
    flexDirection: 'row',
    borderBottom: '2 solid #374151',
    paddingBottom: 8,
    marginBottom: 5,
    backgroundColor: '#F9FAFB',
  },
  tableCell: {
    fontSize: 9,
    color: '#1F2937',
  },
  tableCellHeader: {
    fontSize: 9,
    fontWeight: 'bold',
    color: '#111827',
  },
  badge: {
    padding: '3 8',
    borderRadius: 3,
    fontSize: 8,
    fontWeight: 'bold',
  },
  badgeHigh: {
    backgroundColor: '#FEE2E2',
    color: '#991B1B',
  },
  badgeLimited: {
    backgroundColor: '#FEF3C7',
    color: '#92400E',
  },
  badgeMinimal: {
    backgroundColor: '#D1FAE5',
    color: '#065F46',
  },
  list: {
    marginLeft: 15,
    marginBottom: 10,
  },
  listItem: {
    flexDirection: 'row',
    marginBottom: 5,
  },
  bullet: {
    width: 15,
    fontSize: 10,
    color: '#6B7280',
  },
  listItemText: {
    flex: 1,
    fontSize: 10,
    color: '#1F2937',
  },
});

/**
 * Common header component for all documents
 */
export const PDFHeader = ({
  title,
  subtitle,
  locale = 'en',
}: {
  title: string;
  subtitle: string;
  locale?: string;
}) => (
  <View style={commonStyles.header}>
    <Text style={commonStyles.title}>{title}</Text>
    <Text style={commonStyles.subtitle}>{subtitle}</Text>
    <Text style={[commonStyles.subtitle, { fontSize: 9 }]}>
      {formatDate(new Date(), locale)}
    </Text>
  </View>
);

/**
 * Common footer component with disclaimer
 */
export const PDFFooter = ({
  pageNumber,
  totalPages,
  disclaimerText,
}: {
  pageNumber: number;
  totalPages: number;
  disclaimerText: string;
}) => (
  <View style={commonStyles.footer}>
    <Text style={{ marginBottom: 5 }}>{disclaimerText}</Text>
    <Text>
      Page {pageNumber} of {totalPages} • Generated by Complyance.io
    </Text>
  </View>
);

/**
 * Disclaimer banner
 */
export const Disclaimer = ({ text }: { text: string }) => (
  <View style={commonStyles.disclaimer}>
    <Text style={commonStyles.disclaimerText}>{text}</Text>
  </View>
);

/**
 * Format date based on locale
 */
export function formatDate(date: Date, locale: string = 'en'): string {
  const options: Intl.DateTimeFormatOptions = {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  };

  return new Intl.DateTimeFormat(locale, options).format(date);
}

/**
 * Format date as short format (YYYY-MM-DD)
 */
export function formatDateShort(date: Date): string {
  return date.toISOString().split('T')[0];
}

/**
 * Calculate days until a deadline
 */
export function daysUntil(deadline: Date): number {
  const now = new Date();
  const diff = deadline.getTime() - now.getTime();
  return Math.ceil(diff / (1000 * 60 * 60 * 24));
}

/**
 * Render a React PDF document to Buffer
 */
export async function renderPDF(document: ReactElement): Promise<Buffer> {
  try {
    const stream = await ReactPDF.renderToStream(document);

    return new Promise((resolve, reject) => {
      const chunks: Buffer[] = [];

      stream.on('data', (chunk: Buffer) => chunks.push(chunk));
      stream.on('end', () => resolve(Buffer.concat(chunks)));
      stream.on('error', reject);
    });
  } catch (error) {
    console.error('PDF rendering error:', error);
    throw new Error(`Failed to render PDF: ${error instanceof Error ? error.message : 'Unknown error'}`);
  }
}

/**
 * Get risk level color for badges
 */
export function getRiskLevelColor(riskLevel: string): {
  backgroundColor: string;
  color: string;
} {
  switch (riskLevel) {
    case 'UNACCEPTABLE':
      return { backgroundColor: '#7F1D1D', color: '#FFFFFF' };
    case 'HIGH':
      return { backgroundColor: '#FEE2E2', color: '#991B1B' };
    case 'LIMITED':
      return { backgroundColor: '#FEF3C7', color: '#92400E' };
    case 'MINIMAL':
      return { backgroundColor: '#D1FAE5', color: '#065F46' };
    default:
      return { backgroundColor: '#F3F4F6', color: '#1F2937' };
  }
}

/**
 * Get priority color
 */
export function getPriorityColor(priority: string): {
  backgroundColor: string;
  color: string;
} {
  switch (priority) {
    case 'CRITICAL':
      return { backgroundColor: '#FEE2E2', color: '#991B1B' };
    case 'HIGH':
      return { backgroundColor: '#FED7AA', color: '#9A3412' };
    case 'MEDIUM':
      return { backgroundColor: '#FEF3C7', color: '#92400E' };
    case 'LOW':
      return { backgroundColor: '#DBEAFE', color: '#1E40AF' };
    default:
      return { backgroundColor: '#F3F4F6', color: '#1F2937' };
  }
}
